-- Migration 011: sync_config table
-- ตั้งค่าช่วงเวลาพัก (Quiet Hours) เพื่อประหยัด Tuya API quota
-- ระบบจะไม่เรียก Tuya API ในช่วงที่กำหนด (default 00:00-06:00 เวลาไทย)

CREATE TABLE IF NOT EXISTS sync_config (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiet_hours_enabled BOOLEAN DEFAULT true,
  quiet_hours_start   TEXT DEFAULT '00:00',   -- 24h format, Thai time (UTC+7)
  quiet_hours_end     TEXT DEFAULT '06:00',   -- 24h format, Thai time (UTC+7)
  updated_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_by          TEXT                     -- admin email who last changed
);

-- Seed default: พัก 00:00-06:00 เวลาไทย
INSERT INTO sync_config (quiet_hours_enabled, quiet_hours_start, quiet_hours_end)
VALUES (true, '00:00', '06:00');

-- RLS
ALTER TABLE sync_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read_sync_config" ON sync_config FOR SELECT TO anon USING (true);
CREATE POLICY "anon_update_sync_config" ON sync_config FOR UPDATE TO anon USING (true);
