-- Migration 012: Sync Schedule — วันเก็บข้อมูล + วันหยุดพิเศษ
-- ขยาย sync_config ให้เลือกวันประจำสัปดาห์ได้
-- เพิ่มตาราง sync_holidays สำหรับวันหยุดเฉพาะ (สงกรานต์, วันพิเศษ ฯลฯ)

-- เพิ่ม active_days ใน sync_config (1=จ, 2=อ, 3=พ, 4=พฤ, 5=ศ, 6=ส, 7=อา)
ALTER TABLE sync_config ADD COLUMN IF NOT EXISTS active_days TEXT DEFAULT '1,2,3,4,5';

-- ตาราง วันหยุดพิเศษ
CREATE TABLE IF NOT EXISTS sync_holidays (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date  DATE NOT NULL UNIQUE,
  reason        TEXT,
  created_by    TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE sync_holidays ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read_holidays" ON sync_holidays FOR SELECT TO anon USING (true);
CREATE POLICY "anon_write_holidays" ON sync_holidays FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "anon_update_holidays" ON sync_holidays FOR UPDATE TO anon USING (true);
CREATE POLICY "anon_delete_holidays" ON sync_holidays FOR DELETE TO anon USING (true);
